name: acq-components workflow

on:
    push:
        branches:
            - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo branch is ${{ github.ref_name }} event ${{ github.event_name }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install packages
        run: npm install

      - name: Build project
        run: npm run build

      - name: Build Docs
        run: npm run build-storybook -o docs
